### ISSUE TITLE
How to set Split_K for higher gpu ulitization?

### ISSUE THREAD

**Issue by limertang** [usyd-fsalab/fp6_llm#12]
How to set Split_K for higher gpu ulitization on Nvidia A800 or RTX4090?

**Comment by Summer-Summer** [comment]
The easiest way is to try different SplitK for the given MatMul shape and observe the execution latency.
You can start with 1.

**Comment by Summer-Summer** [comment]
Let me add a simple heuristic function to choose Splitk to this repo now. It should give you a pretty good splitK (perhaps not the best splitK) for different shapes.

**Comment by Summer-Summer** [comment]
I have added this function to the repo. Can you try it and see if this solves your problem?

import fp6_llm
SplitK = fp6_llm.HeuristicFuntion_SplitK(M, N, Number_GPU_SMs)

Arguments:
    M is the number of rows of the weight matrix, N is the inference batch size. More specifically, the shape of the MulMal: (M, K) * (K, N) -> (M, N), 
    Number_GPU_SMs is the number of Stream Multiprocessors of the GPU you are using. For A100 GPUs, Number_GPU_SMs=108.

**Comment by limertang** [comment]
ok,I'll try it,thank you.

**Comment by limertang** [comment]
I have 2 questions about the code.
1. Num_Wave = math.ceil(M/512) * math.ceil(N/64) * SplitK / Num_GPU_SMs
Q:What's the mean of 512 and 64? Do these values have relations to Num_GPU_SMs?
2. for i in range(1, 100)
Q: Does it means that the max value of splitk is 99 regardless of the GPU arch?

**Comment by Summer-Summer** [comment]
512 and 64 are constants here and unrelated to the GPU arch.
Usually, SplitK will not be larger than 100, according to my experience. If SplitK is larger than that, the overall kernel performance could be very poor.
