### ISSUE TITLE
FP6-BF16 support added to torchao

### ISSUE THREAD

**Issue by tobiasvanderwerff** [usyd-fsalab/fp6_llm#13]
Hi, thanks for your work! As you may know, your kernel is currently integrated into [pytorch/ao](https://github.com/pytorch/ao). I thought I would let you know that In an effort to make your work even more accesible, I recently made an effort to modify your kernel to support BF16 in addition to FP16. You can find the relevant PR here: https://github.com/pytorch/ao/pull/1147.

If you have any comments or suggestions, feel free to let me know.

**Comment by Summer-Summer** [comment]
Thanks so much for making our work more accessible! I will take a look at it!
