### ISSUE TITLE
Has the accuracy and performance been compared with awq？

### ISSUE THREAD

**Issue by dingjingzhen** [usyd-fsalab/fp6_llm#4]
Has the accuracy and performance been compared with awq int4？

**Comment by catid** [comment]
Should read their github blog post - It performs much better

**Comment by Summer-Summer** [comment]
At the time when we were writing the research paper, TensorRT-LLM's W4A16 kernel was faster than AWQ's W4A16 kernel, so we compared our kernel performance with TensorRT-LLM's W4A16 kernel.
According to [this figure](https://github.com/usyd-fsalab/fp6_llm/blob/main/docs/figures/Speedup_to_4bit.png), our FP6 kernel achieves similar performance with fine-grained W4A16 kernel and is slightly slower than coarse-grained W4A16.
As for accuracy, coarse-grained W4A16 shows quite bad results. We also found that FP6 quantization is more robust than INT4. Please also refer to [this paper](https://arxiv.org/abs/2312.08583) for more insights related to model accuracy.
