### ISSUE TITLE
Can we get FP4?

### ISSUE THREAD

**Issue by catid** [usyd-fsalab/fp6_llm#5]
FP6 doesn't seem to be a useful size.  The best models are 70B that we can run, and only 4 bit models will fit in ~40-48GB VRAM

**Comment by Summer-Summer** [comment]
We will support FP5 soon. Yeah, I will try to also support FP4.

**Comment by Summer-Summer** [comment]
I have added support for fp5 and tested it.
I did not test fp4 myself, but it should work.
