### ISSUE TITLE
Does fp6 need a calibration dataset to tune with?

### ISSUE THREAD

**Issue by leiwen83** [usyd-fsalab/fp6_llm#7]
And have fp6 compare the accuracy with fp8? I haven't find any related in the paper...

**Comment by Summer-Summer** [comment]
Yeah, we only compared the accuracy to FP16 and the accuracy loss is already negligible. We did not further compare it to FP8 because FP8 would not be better than FP16.

**Comment by Summer-Summer** [comment]
For FP6, we can do post-training quantization. I think we do not need a calibration dataset. Please refer to https://arxiv.org/abs/2312.08583 for more algorithm level details.
